package my.pack.model;

// Generated 2013-11-04 21:27:42 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS", schema = "PUBLIC", catalog = "PHONEBOOK")
public class Address implements java.io.Serializable {

	private Integer idAddress;
	private Item item;
	private String line1;
	private String line2;

	public Address() {
	}

	public Address(Item item, String line1, String line2) {
		this.item = item;
		this.line1 = line1;
		this.line2 = line2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_address", unique = true, nullable = false)
	public Integer getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(Integer idAddress) {
		this.idAddress = idAddress;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_item")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "line1", length = 45)
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(name = "line2", length = 45)
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

}
