package my.pack.model;

// Generated 2013-11-04 21:27:42 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "ITEM", schema = "PUBLIC", catalog = "PHONEBOOK")
public class Item implements java.io.Serializable {

	private Integer idItem;
	private String firstName;
	private String lastName;
	private Set<Phone> phones = new HashSet<Phone>(0);
	private Set<Address> addresses = new HashSet<Address>(0);

	public Item() {
	}

	public Item(String firstName, String lastName, Set<Phone> phones,
			Set<Address> addresses) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phones = phones;
		this.addresses = addresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idItem", unique = true, nullable = false)
	public Integer getIdItem() {
		return this.idItem;
	}

	public void setIdItem(Integer idItem) {
		this.idItem = idItem;
	}

	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<Phone> getPhones() {
		return this.phones;
	}

	public void setPhones(Set<Phone> phones) {
		this.phones = phones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	public List<Address> getAddressesAsList() {
		return new ArrayList<Address>(this.addresses);
	}

	public List<Phone> getPhonesAsList() {
		return new ArrayList<Phone>(this.phones);
	}
}
