package my.pack.model;

// Generated 2013-11-06 08:05:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "TEST", schema = "PUBLIC", catalog = "PHONEBOOK")
public class Test implements java.io.Serializable {

	private int id;
	private String name;

	public Test() {
	}

	public Test(int id) {
		this.id = id;
	}

	public Test(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
